---
os:
  - osx

language: python
python: "2.7"

install:
  - pip install --upgrade pip
  - pip install ansible
  - mv tests/ansible.cfg .

script:
  - ls -hal
  - cat ansible.cfg
  - cat tests/inventory
  - ansible-playbook tests/test.yml
