---
os: osx
osx_image: xcode10.2

install:
  - which scutil
  - scutil --set LocalHostName "TravisCI"
  - scutil --set ComputerName "Travis Mac"
  - pip install --upgrade pip
  - pip install ansible
  - mv tests/ansible.cfg .

script:
  - ansible-playbook tests/test.yml --connection=local -vv
