---
# HostName tasks file for ansible-role-macos-hostname.
#
# Derives (if necessary) and sets HostName

- name: Determine the desired macOS HostName value.
  set_fact:
    mh_derived_hostname: "{{ (mh_hostname == 'auto') | ternary(mh_derived_product_lower + '.' + mh_domain, mh_hostname) }}"
  when: "mh_hostname is defined or mh_hostname"

- name: Set macOS hostname.
  command: "scutil --set HostName {{ mh_hostname }}"
  when: "mh_derived_hostname is defined"
  become: true
