---
# HostName tasks file for ansible-role-macos-hostname.
#
# Sets HostName.

- name: Find out the current macOS HostName value.
  command: "scutil --get HostName"
  register: "mh_current_hostname"
  changed_when: false
  # If the HostName is not set--this is often true, `scutil --get HostName`
  # returns an error code (d'oh!) with the empty string stdout that we _want_.
  failed_when: false

- name: Set macOS HostName.
  command: "scutil --set HostName {{ mh_hostname }}"
  when:
    - "mh_hostname != mh_current_hostname.stdout"
  become: true
  notify: clear dns cache
